name: Build Rust ARM64

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-aarch64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build Release Binary
        run: cross build --target aarch64-unknown-linux-gnu --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-aarch64
          path: target/aarch64-unknown-linux-gnu/release/<YOUR_BINARY_NAME>
